### PR TITLE
[Fix #4265] Porting frontend docsearch to work with new API

### LINKED ISSUE #4265: Port Document search API for Elasticsearch 6.x
For Document search functionality, there are already an API exist in `readthedocs-ext` repository.
As we upgrade the search as part of GSOC project, that API need to be ported to work with the new search infrastructure. The search API should be rewritten by using the `PageDocument` class but the API schema should not be changed. That will be a complex work to do as the API schema need to be kept same.

Before starting work, there should be good amount of test in the current API schema because if API schema is changed, document search will be broken in the frontend and it will have major effect. See #4197 for ongoing tests.

@ericholscher @agjohnson Do you think the API schema should be kept same or we should design a new Document Search API which mataches with the new search upgrade code?

### PR DESCRIPTION
**Pull request by safwanrahman**
This fixes #4265 
I have ported the existing search javascript in order to work with the new Restful search API. The API   has been implemented in #4309.

@ericholscher @davidfischer r?

### CODE REVIEW

File: readthedocs/core/static-src/core/js/doc-embed/search.js [hunk 1]
```diff
@@ -23,48 +23,48 @@ function attach_elastic_search_query(data) {
...
-                        // fields.project is returned as an array
-                        if (fields.project.indexOf(project) === -1) {
-                            list_item.append(
-                                $('<span>')
-                                .text(" (from project " + fields.project + ")")
-                            );
+                    for (var i = 0; i < hit_list.length; i += 1) {
+                        var document = hit_list[i];
+                        var highlight = document.highlight;
+                        var $list_item = $('<li style="display: none;"></li>');
```
Comment (ericholscher) [inline readthedocs/core/static-src/core/js/doc-embed/search.js]: I see what you're doing here, but we don't follow this convention anywhere else in the code, so we shouldn't do it here to be consistent.

File: readthedocs/core/static-src/core/js/doc-embed/search.js [hunk 2]
```diff
@@ -23,48 +23,48 @@ function attach_elastic_search_query(data) {
...
+                            $list_item.append($extra);
                         }
-                        if (highlight.content.length) {
-                            var content = $('<div class="context">')
-                                .html(xss(highlight.content[0]));
-                            content.find('em').addClass('highlighted');
-                            list_item.append(content);
+
+                        // Show highlighted texts
+                        if (highlight.content) {
```
Comment (ericholscher) [inline readthedocs/core/static-src/core/js/doc-embed/search.js]: Do we not need to check `length` here? I don't know JS well enough, but that's what we were doing before, so probably worth keeping it explicit.

Comment (safwanrahman) [reply readthedocs/core/static-src/core/js/doc-embed/search.js]: In the previous API, the `content` was provided as a blank list if there are no match in content. but our current API do not provide anything in the `content` key if there are not anything in the content. So checking the length may raise error.

File: readthedocs/core/static-src/core/js/doc-embed/search.js [hunk 3]
```diff
@@ -23,48 +23,48 @@ function attach_elastic_search_query(data) {
...
-                            .attr('href', item_url)
-                            .html(fields.title)
-                        );
-                        // fields.project is returned as an array
-                        if (fields.project.indexOf(project) === -1) {
-                            list_item.append(
-                                $('<span>')
-                                .text(" (from project " + fields.project + ")")
-                            );
+                    for (var i = 0; i < hit_list.length; i += 1) {
```
Comment (agjohnson) [inline readthedocs/core/static-src/core/js/doc-embed/search.js]: `for (var n in hit_list)` is a more readable iteration format and is support down to ie6

File: readthedocs/core/static-src/core/js/doc-embed/search.js [hunk 4]
```diff
@@ -23,48 +23,48 @@ function attach_elastic_search_query(data) {
...
+                        var doc = hit_list[i];
+                        var highlight = doc.highlight;
+                        var $list_item = $('<li style="display: none;"></li>');
```
Comment (agjohnson) [inline readthedocs/core/static-src/core/js/doc-embed/search.js]: for consistency, we don't prefix vars with `$`

File: readthedocs/core/static-src/core/js/doc-embed/search.js [hunk 5]
```diff
@@ -23,48 +23,48 @@ function attach_elastic_search_query(data) {
...
+
+                        // Creating the result from elements
+                        var link = doc.link + DOCUMENTATION_OPTIONS.FILE_SUFFIX +
+                                   '?highlight=' + $.urlencode(query);
+
+                        var $item = $('<a>', {'href': link});
```
Comment (agjohnson) [inline readthedocs/core/static-src/core/js/doc-embed/search.js]: same `$` prefix

File: readthedocs/core/static-src/core/js/doc-embed/search.js [hunk 6]
```diff
@@ -23,48 +23,48 @@ function attach_elastic_search_query(data) {
...
+                        $item.html(doc.title);
+                        $list_item.append($item);
+
+                        // If the document is from subproject, add extra information
+                        if (doc.project !== project) {
```
Comment (agjohnson) [inline readthedocs/core/static-src/core/js/doc-embed/search.js]: Be careful that this doesn't revert to buggy behavior, if the return attribute`doc.proejct` hasn't changed. The equivalent of `doc.project` in the current js is always an array, so `doc.project !== project` is false because `doc.project = ['docs']` and `project = 'docs'`

File: readthedocs/core/static-src/core/js/doc-embed/search.js [hunk 7]
```diff
@@ -23,48 +23,48 @@ function attach_elastic_search_query(data) {
...
+                            var text = " (from project " + doc.project + ")";
+                            var $extra = $('<span>', {'text': text});
```
Comment (agjohnson) [inline readthedocs/core/static-src/core/js/doc-embed/search.js]: more `$` prefix

File: readthedocs/core/static-src/core/js/doc-embed/search.js [hunk 8]
```diff
@@ -23,48 +23,48 @@ function attach_elastic_search_query(data) {
...
-                        if (highlight.content.length) {
-                            var content = $('<div class="context">')
-                                .html(xss(highlight.content[0]));
-                            content.find('em').addClass('highlighted');
-                            list_item.append(content);
+
+                        // Show highlighted texts
+                        if (highlight.content) {
+                            var content_text = xss(highlight.content[0]);
+                            var $contents = $('<div class="context">');
```
Comment (agjohnson) [inline readthedocs/core/static-src/core/js/doc-embed/search.js]: More `$` prefix

File: readthedocs/core/static-src/core/js/doc-embed/search.js [hunk 9]
```diff
@@ -96,11 +96,11 @@ function attach_elastic_search_query(data) {
                 withCredentials: true,
             },
             complete: function (resp, status_code) {
-                if (typeof (resp.responseJSON) === 'undefined' ||
-                        typeof (resp.responseJSON.results) === 'undefined') {
+                console.log(status_code);
```
Comment (agjohnson) [inline readthedocs/core/static-src/core/js/doc-embed/search.js]: Debug logging can be removed

File: readthedocs/core/static-src/core/js/doc-embed/search.js (hunk 6 above)
Comment (safwanrahman) [reply readthedocs/core/static-src/core/js/doc-embed/search.js]: As discussed over slack, the new API always return `String`, instead of list.

**Comment by ericholscher** [comment]
👍 on resyncing the `search_upgrade` branch with master, we can do that after this PR though I think.

**Comment by safwanrahman** [comment]
@davidfischer Yes. there are lot of conflicts as the branch is old. Can you cherry pick your asset generation commits to the branch and generate assets to test?

@ericholscher I am hoping to rebase the `search_upgrade` branch with master. so the conflict will be gone away! There are big conflict actually that need to be handeled well.

**Comment by safwanrahman** [comment]
@agjohnson I have fixed the issue as you have mentioned. r?

**Comment by safwanrahman** [comment]
@ericholscher possible to merge?
