### PR TITLE
Fix resync remote repos

### LINKED ISSUE #4101: Project import remote repository sync doesn't sync when org selected
Steps to reproduce it:

1. go to "Import Project"
1. filter by your service (i.e. GitLab)
1. you will see the list of your repos under that service
1. go to the service page (i.e. gitlab.com)
1. create a repo there
1. go back to RTD import page
1. click on sync

When sync is finished you won't see your new repository there to be imported as project. You will have to refresh the page or filter by another category and filter back by your username.

This is because when the sync finishes, there is no request made to 

    https://readthedocs.com/api/v2/remote/repo/?own=gitlab

where `own` is the filter selected.

### PR DESCRIPTION
**Pull request by stsewd**
Fix #4101

I'll re-minify the js after see if this is the correct solution p:

### CODE REVIEW

File: readthedocs/projects/static-src/projects/js/import.js [hunk 1]
```diff
@@ -282,6 +282,8 @@ function ProjectImportView(instance, config) {
             .then(function (data) {
                 self.get_organizations();
                 self.get_accounts();
+                // re-sync
+                self.filter_by(self.filter_by());
```
Comment (stsewd) [inline readthedocs/projects/static-src/projects/js/import.js]: I'm not sure if this is the proper way of doing this, but I didn't find anything on the docs. But I tested this and works as expected.

File: readthedocs/projects/static-src/projects/js/import.js [hunk 2]
```diff
@@ -282,6 +282,8 @@ function ProjectImportView(instance, config) {
             .then(function (data) {
                 self.get_organizations();
                 self.get_accounts();
+                // re-sync
```
Comment (humitos) [inline readthedocs/projects/static-src/projects/js/import.js]: It's not a re-sync but a filter by previously selected filter

File: readthedocs/projects/static-src/projects/js/import.js (hunk 1 above)
Comment (humitos) [reply readthedocs/projects/static-src/projects/js/import.js]: Did you test it locally? The line looks fine to me.

Don't we need to re-request the projects also and then apply the filter?

Comment (stsewd) [reply readthedocs/projects/static-src/projects/js/import.js]: > Did you test it locally? The line looks fine to me.

Yes, I tested locally, it works.

> Don't we need to re-request the projects also and then apply the filter?

When the filter is set, a new request is made https://github.com/rtfd/readthedocs.org/pull/4113/files#diff-fd74ba503cde92cdf9a406ce7da32f2eL210.

File: readthedocs/projects/static-src/projects/js/import.js (hunk 2 above)
Comment (stsewd) [reply readthedocs/projects/static-src/projects/js/import.js]: But this is a _hack_ to trigger the re-sync

Comment (humitos) [reply readthedocs/projects/static-src/projects/js/import.js]: yeah, you are right. So, maybe it's better to improve the comment explaining why we are doing this here and how it works behind the scenes.

File: readthedocs/projects/static-src/projects/js/import.js [hunk 3]
```diff
@@ -282,6 +282,9 @@ function ProjectImportView(instance, config) {
             .then(function (data) {
                 self.get_organizations();
                 self.get_accounts();
+                // This will trigger a new
+                // request to re-sync the repos
+                self.filter_by(self.filter_by());
```
Comment (agjohnson) [inline readthedocs/projects/static-src/projects/js/import.js]: I believe the observable should have a `notifySubscribers` method that we can call, instead of resetting the variable like this to notify subscribing observables.

Comment (stsewd) [reply readthedocs/projects/static-src/projects/js/import.js]: I'll try to take a deeper look to the docs and see what I can find.

File: readthedocs/projects/static-src/projects/js/import.js [hunk 4]
```diff
@@ -282,6 +282,9 @@ function ProjectImportView(instance, config) {
             .then(function (data) {
                 self.get_organizations();
                 self.get_accounts();
+                // This will trigger a new
+                // request to re-sync the repos
+                self.filter_by.valueHasMutated();
```
Comment (stsewd) [inline readthedocs/projects/static-src/projects/js/import.js]: I took this from https://stackoverflow.com/questions/16261689/force-knockout-to-mark-an-observable-as-changed-even-if-focus-is-still-in-the-f#16261761, still not sure if this is the correct way, but I tested and works.

Comment (agjohnson) [reply readthedocs/projects/static-src/projects/js/import.js]: This change looks better.

**Comment by agjohnson** [comment]
This will need a rebase and regeneration of the static assets.

**Comment by stsewd** [comment]
Done
